# Generated by Django 5.1.4 on 2025-08-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaidya_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupDOCTORS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('specialisation', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('ngo', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
