# Generated by Django 5.1.4 on 2025-08-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaidya_app', '0003_signupngo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('doctor', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('diagnosis_report', models.FileField(blank=True, null=True, upload_to='diagnosis_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
