# Generated by Django 5.1.4 on 2025-08-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaidya_app', '0004_consultationbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Illness', 'Illness'), ('Outbreak', 'Outbreak'), ('Mental Health Crisis', 'Mental Health Crisis')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
