# Generated by Django 5.1.4 on 2025-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaidya_app', '0005_healthreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='gmeet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
