# Generated by Django 5.1.4 on 2025-08-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaidya_app', '0006_consultationbooking_gmeet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='schedule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
