# Generated by Django 5.1.4 on 2025-08-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaidya_app', '0007_consultationbooking_schedule_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('health', 'Health Camp'), ('education', 'Education Drive'), ('environment', 'Environment Awareness'), ('charity', 'Charity Event')], max_length=20)),
            ],
        ),
    ]
